/* eslint-disable @typescript-eslint/no-explicit-any */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import { GroupProps } from '@react-three/fiber';

export function CasquetteModel(props: GroupProps) {
  const { nodes, materials } = useGLTF('/cap.glb') as any;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Hatt.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brimes.geometry}
        material={materials['Material.002']}
        position={[0, -1.473, 0.007]}
        rotation={[0.258, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus.geometry}
        material={materials['Material.004']}
        position={[-0.353, -0.524, 0.743]}
        rotation={[0.425, -0.292, 0.06]}
        scale={[0.075, 0.075, 0.015]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus001.geometry}
        material={materials['Material.004']}
        position={[0.299, -0.578, 0.735]}
        rotation={[0.435, 0.262, 0.024]}
        scale={[0.075, 0.075, 0.015]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus002.geometry}
        material={materials['Material.004']}
        position={[0.619, -0.015, 0.747]}
        rotation={[0.016, 0.535, 0.155]}
        scale={[0.075, 0.075, 0.015]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus003.geometry}
        material={materials['Material.004']}
        position={[0.307, 0.546, 0.737]}
        rotation={[-0.514, 0.235, 0.305]}
        scale={[0.075, 0.075, 0.015]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus004.geometry}
        material={materials['Material.004']}
        position={[-0.258, 0.558, 0.743]}
        rotation={[-0.524, -0.218, 0.24]}
        scale={[0.075, 0.075, 0.015]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus005.geometry}
        material={materials['Material.004']}
        position={[-0.652, 0.008, 0.727]}
        rotation={[-0.017, -0.535, 0.391]}
        scale={[0.075, 0.075, 0.015]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={materials['Material.003']}
        position={[-0.453, -1.017, 0.292]}
        rotation={[1.536, 0, 0]}
        scale={0.277}
      />
    </group>
  );
}

useGLTF.preload('/cap.glb');
